### ISSUE TITLE
まな板mod

### ISSUE THREAD

**Issue by miku1881** [takusan23/ClickManaita2#1]
1.18.2のforge版作ってください

**Comment by takusan23** [comment]
Forge 1.18版があるのでそんなに大変じゃないはず、作ります :octocat:

**Comment by takusan23** [comment]
おはようございます。
https://www.curseforge.com/minecraft/mc-mods/clickmanaita/files/3842732

1.18.2 の Forge 版できました、多分起動できると思います。
