### ISSUE TITLE
Regarding the improvement plan for all versions

### ISSUE THREAD

**Issue by TheDesiringOne** [takusan23/ClickManaita2#2]
It's a pity that all the content from the old version, such as weapons and armor, has not been ported to the new version. I wonder if it's possible to stop updating with higher versions in the future and instead fill in all the content from different versions? After all, the content of this mod module is still too empty now.

**Comment by takusan23** [comment]
Most items and blocks are still available in the new version.
(Manaita Pickaxe has been changed to enchantment)

Can you tell me specifically what is missing?
Also, this mod doesn't have any armor, so it might be a different mod.

Thanks.

--- 日本語 ---

```plaintext
ほとんどのアイテムやブロックは、新バージョンでも利用可能です。
（まな板つるはしはエンチャントに変更されました）

具体的には何が足りないか教えてもらえますか？
また、この MOD には防具が無いため、もしかすると違う MOD の可能性があります。

ありがとう。
```

**Comment by TheDesiringOne** [comment]
It's mainly because of the name ClickManaita2, thinking that the content of Manaita Plus would be transplanted to a higher version. But, it's true that the two are completely different. Your mod emphasizes Click, while Manaita Plus does not. So, your mod is different from it, with completely different concepts and directions. So, I apologize for any offense.

**Comment by takusan23** [comment]
Oh, no problem! I understand.
🙂
